/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Laptop.glb -o src/components/Portfolio/PortfolioLaptop.jsx -k -r public 
*/

import React from "react";
import { useGLTF, Float, useTexture } from "@react-three/drei";
import { motion } from "framer-motion-3d";

export function PortfolioLaptop(props) {
  const { nodes, materials } = useGLTF(
    import.meta.env.BASE_URL + "/models/Laptop.glb"
  );
  const screenTexture = useTexture("images/personal.png");
  const transition = {
    delay: 0.2,
    duration: 3,
    ease: [0.25, 1, 0.5, 1],
  };
  return (
    <group {...props} dispose={null}>
      <Float
        floatIntensity={1}
        speed={2}
        rotationIntensity={0}
        floatingRange={[0, 0.2]}
      >
        <group
          name="Cube"
          position={[0, -0.127, 0.164]}
          scale={[1.387, 0.053, 0.939]}
        >
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cube001_2"
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Cube001"
          position={[0, 0.893, -0.712]}
          scale={[1.389, 0.986, 0.066]}
        >
          <mesh
            name="Cube002_1"
            geometry={nodes.Cube002_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cube002_2"
            geometry={nodes.Cube002_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Cube002"
          position={[-0.019, -0.096, 0]}
          scale={[1.042, 0.04, 0.512]}
        >
          <mesh
            name="Cube003"
            geometry={nodes.Cube003.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cube003_1"
            geometry={nodes.Cube003_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane"
          position={[0, 0.888, -0.631]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.073, 1, 0.726]}
        >
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry}>
            <meshStandardMaterial map={screenTexture} />
          </mesh>
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </Float>
    </group>
  );
}

useGLTF.preload(import.meta.env.BASE_URL + "/models/Laptop.glb");
useTexture.preload("images/personal.png");
