/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/portfoliohome.glb -o src/components/Portfolio/PortfolioHome.jsx -k -r public 
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, Float } from "@react-three/drei";
import { motion } from "framer-motion-3d";

export function PortfolioHome(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(
    import.meta.env.BASE_URL + "models/portfoliohome.glb"
  );

  const transition = {
    delay: 0.2,
    duration: 3,
    ease: [0.25, 1, 0.5, 1],
  };

  // cloud coming out of chimney ani
  const bigCloudRef = useRef();
  const cloudHRef = useRef();
  const cloudLRef = useRef();

  useFrame((state, delta) => {
    const clouds = [bigCloudRef, cloudHRef, cloudLRef];

    clouds.forEach((cloudRef) => {
      if (cloudRef.current) {
        cloudRef.current.position.y += delta * 0.3; // smoke rise speed

        // If cloud goes too high, reset to bottom
        if (cloudRef.current.position.y > 8) {
          cloudRef.current.position.y = 4.5 + Math.random() * 0.5; // randomize a bit for realism
        }
      }
    });
  });

  return (
    <group
      {...props}
      rotation-y={-0.75}
      // position={(-2.5, 1, 0)} mobile later
      position={[-4.5, 0.1, 0]}
      ref={groupRef}
      dispose={null}
    >
      <Float
        floatIntensity={1}
        speed={2}
        rotationIntensity={0}
        floatingRange={[0, 0.2]}
      >
        <motion.group
          position-y={50}
          transition={transition}
          variants={{
            Home: {
              y: 0,
            },
          }}
        >
          <group
            name="House"
            position={[-2.938, 1.181, -3.562]}
            scale={[1.353, 1, 1.282]}
          >
            <mesh
              name="Cube002"
              geometry={nodes.Cube002.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials["Material.009"]}
            />
          </group>
          <group name="Door" position={[-2.18, 0, -3.368]} scale={[1, 1, 0.57]}>
            <mesh
              name="Cube003"
              geometry={nodes.Cube003.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Cube003_1"
              geometry={nodes.Cube003_1.geometry}
              material={materials["Material.014"]}
            />
          </group>
          <group
            name="WindowL"
            position={[0, 2.186, -2.56]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -0.532, -0.321]}
          >
            <mesh
              name="Cube005"
              geometry={nodes.Cube005.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Cube005_1"
              geometry={nodes.Cube005_1.geometry}
              material={materials["Material.014"]}
            />
          </group>
          <group
            name="Chimney"
            position={[-2.949, 3.532, -4.941]}
            rotation={[-0.493, 0, 0]}
            scale={0.414}
          >
            <mesh
              name="Plane004"
              geometry={nodes.Plane004.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Plane004_1"
              geometry={nodes.Plane004_1.geometry}
              material={materials["Material.009"]}
            />
          </group>
          <group
            ref={bigCloudRef}
            name="Big_Cloud"
            position={[-2.636, 4.861, -5.216]}
            rotation={[-0.017, 0.165, -0.713]}
            scale={[2.129, 1, 1]}
          >
            <mesh
              name="Sphere_1"
              geometry={nodes.Sphere_1.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Sphere_2"
              geometry={nodes.Sphere_2.geometry}
              material={materials["Material.001"]}
            />
          </group>

          <group
            ref={cloudHRef}
            name="CloudH"
            position={[-2.636, 6.401, -4.942]}
            scale={-0.501}
          >
            <mesh
              name="Sphere001"
              geometry={nodes.Sphere001.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Sphere001_1"
              geometry={nodes.Sphere001_1.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <group
            ref={cloudLRef}
            name="CloudL"
            position={[-2.952, 4.921, -4.942]}
            scale={-0.412}
          >
            <mesh
              name="Sphere002"
              geometry={nodes.Sphere002.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Sphere002_1"
              geometry={nodes.Sphere002_1.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials.Material}
            position={[-2.65, 3.001, -3.609]}
          />
        </motion.group>
        <motion.group
          position-y={-10}
          transition={transition}
          variants={{
            Home: {
              y: 0,
            },
          }}
        >
          <group
            name="Floor"
            position={[-2.949, 3.532, -4.941]}
            rotation={[-0.493, 0, 0]}
            scale={0.414}
          >
            <mesh
              name="Plane001"
              geometry={nodes.Plane001.geometry}
              material={materials.seethru}
            />
            <mesh
              name="Plane001_1"
              geometry={nodes.Plane001_1.geometry}
              material={materials["Material.016"]}
            />
          </group>
        </motion.group>
      </Float>
    </group>
  );
}

useGLTF.preload(import.meta.env.BASE_URL + "models/portfoliohome.glb");
