/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/portfolioscene.glb -o src/components/Portfolio/PortfolioScene.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PortfolioScene(props) {
  const { nodes, materials } = useGLTF(
    import.meta.env.BASE_URL + "models/portfolioscene.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        position={[0, 0, 80.193]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[129.4, 402.537, 0.413]}
      />
      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        position={[0, 0, 80.193]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[900.284, 402.537, 0.413]}
      />

      <group name="Sphere" position={[-0.923, 9.178, 102.025]} scale={3.513}>
        <mesh
          name="Sphere_1"
          geometry={nodes.Sphere_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          name="Sphere_2"
          geometry={nodes.Sphere_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(import.meta.env.BASE_URL + "models/portfolioscene.glb");
