/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/TV.glb -o src/components/Portfolio/PortfolioTV.jsx -k -r public 
*/
import { useEffect, useMemo, useRef, useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { useAtom } from "jotai";
import { projectAtom } from "./Interface";
import { config } from "../../config";
import { useFrame } from "@react-three/fiber";

export function PortfolioTV(props) {
  const { nodes, materials } = useGLTF(
    import.meta.env.BASE_URL + "models/TV.glb"
  );

  const [project] = useAtom(projectAtom);
  const imageTexture = useTexture(project.image);
  const videoRef = useRef(null);
  const [texture, setTexture] = useState(null);

  const isVideo = project.clip?.endsWith(".mp4");
  useEffect(() => {
    let video;
    let isMounted = true;

    if (isVideo) {
      video = document.createElement("video");
      video.src = project.clip;
      video.loop = true;
      video.muted = true;
      video.playsInline = true;
      video.autoplay = true;

      video.addEventListener("canplay", () => {
        if (!isMounted) return;

        video.play();

        const videoTex = new THREE.VideoTexture(video);
        videoTex.center.set(0.5, 0.5);
        videoTex.rotation = Math.PI / 2;
        videoTex.repeat.x = -1;

        setTexture(videoTex);
      });

      videoRef.current = video;
    } else if (imageTexture) {
      imageTexture.center.set(0.5, 0.5);
      imageTexture.rotation = Math.PI / 2;
      imageTexture.repeat.x = -1;

      setTexture(imageTexture);
    }

    return () => {
      isMounted = false;
      if (video) {
        video.pause();
        video.src = "";
        video.load(); // release memory
      }
    };
  }, [project.clip, project.image, isVideo, imageTexture]);

  const emissiveRef1 = useRef();
  const emissiveRef2 = useRef();

  useFrame(() => {
    if (emissiveRef1.current) {
      emissiveRef1.current.emissiveIntensity = Math.random() > 0.9 ? 2.5 : 1.2;
    }
    if (emissiveRef2.current) {
      emissiveRef2.current.emissiveIntensity = Math.random() > 0.8 ? 2 : 1;
    }
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={0.8}
      position={[3, 0.45, 0]}
      rotation={[0, -2.1, 0]}
    >
      <group
        name="Cube"
        position={[-0.055, 4.033, 0]}
        scale={[-2.064, -3.672, -4.819]}
      >
        <mesh
          name="Cube_1"
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          name="Cube_2"
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        name="Plane"
        position={[2.157, 0.911, -3.016]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.283, 0.307, 0.283]}
      >
        <mesh name="Plane002" geometry={nodes.Plane002.geometry}>
          <meshStandardMaterial
            ref={emissiveRef1}
            emissive="#39ff14"
            emissiveIntensity={1.5}
            metalness={0.3}
            color="black"
            opacity={1}
          />
        </mesh>
        <mesh
          name="Plane002_1"
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        name="Plane001"
        position={[2.157, 0.911, -2.196]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.283, 0.307, 0.283]}
      >
        <mesh name="Plane003" geometry={nodes.Plane003.geometry}>
          <meshStandardMaterial
            ref={emissiveRef2}
            emissive="#ff2400"
            emissiveIntensity={1.5}
            metalness={0.3}
            color="black"
            opacity={1}
          />
        </mesh>
        <mesh
          name="Plane003_1"
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        name="Screen"
        position={[2.157, 4.078, 0.122]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[3.118, 1.961, 3.399]}
      >
        {texture && (
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry}>
            <meshBasicMaterial map={texture} />
          </mesh>
        )}
        <mesh
          name="Plane_2"
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        name="Legs"
        geometry={nodes.Legs.geometry}
        material={materials["Material.006"]}
        position={[1.246, -0.14, 3.157]}
      />
      {/* <mesh
        name="Sphere"
        geometry={nodes.Sphere.geometry}
        material={materials["Material.007"]}
        position={[-0.235, 6.335, 0.188]}
      /> */}
    </group>
  );
}

config.AcademicProjects.forEach((project) => {
  useTexture.preload(project.image);
});
config.AcademicProjects.forEach((project) => {
  useTexture.preload(project.clip);
});
useGLTF.preload(import.meta.env.BASE_URL + "models/TV.glb");
