/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/portfolioscene.glb -o src/components/Portfolio/PortfolioScene.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PortfolioScene(props) {
  const { nodes, materials } = useGLTF("/models/portfolioscene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Sun"
        geometry={nodes.Sun.geometry}
        material={materials["Material.001"]}
      />
      {/* <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={materials["Mirror Surface"]}
      />
      <mesh
        name="Plane001_1"
        geometry={nodes.Plane001_1.geometry}
        material={materials["Wire Floor"]}
      /> */}
      <mesh
        name="Plane002"
        geometry={nodes.Plane002.geometry}
        material={materials["Mirror Surface.001"]}
      />
      <mesh
        name="Plane002_1"
        geometry={nodes.Plane002_1.geometry}
        material={materials.Mountains}
      />
      <mesh
        name="Plane004"
        geometry={nodes.Plane004.geometry}
        material={materials["Mirror Surface.003"]}
      />
      <mesh
        name="Plane004_1"
        geometry={nodes.Plane004_1.geometry}
        material={materials["Mountains.001"]}
      />
      <mesh
        name="Plane005"
        geometry={nodes.Plane005.geometry}
        material={materials["Mirror Surface.004"]}
      />
      <mesh
        name="Plane005_1"
        geometry={nodes.Plane005_1.geometry}
        material={materials["Mountains.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/portfolioscene.glb");
