// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/models/laptop.glb -o src/components/StartingScreen/Laptop.jsx -k -r public
// Author: jc1245 (https://sketchfab.com/jasperchui2007)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/apple-macbook-pro-16-inch-2021-6a42b31bac064b00a91fbfebec07c852
// Title: Apple MacBook Pro 16 inch 2021
// */

// import React from "react";
// import { useGLTF } from "@react-three/drei";

// export function Laptop(props) {
//   const { nodes, materials } = useGLTF(
//     import.meta.env.BASE_URL + "models/laptop.glb"
//   );
//   return (
//     <group
//       {...props}
//       scale={0.2}
//       rotation={[0, 1, 0]}
//       position={[-0.2, -0.5, 2]}
//       dispose={null}
//     >
//       <group
//         name="Cube016_2"
//         position={[0, 0.1, -1.012]}
//         rotation={[-1.925, 0, 0]}
//         // rotation={[-0.005, 0, 0]}
//       >
//         <mesh
//           name="Object_17"
//           geometry={nodes.Object_17.geometry}
//           material={materials["Material.003"]}
//         />
//         <mesh
//           name="Object_18"
//           geometry={nodes.Object_18.geometry}
//           material={materials["Material.007"]}
//         />
//         <mesh
//           name="Object_19"
//           geometry={nodes.Object_19.geometry}
//           material={materials["Material.006"]}
//         />
//         <mesh
//           name="Object_20"
//           geometry={nodes.Object_20.geometry}
//           material={materials["Material.005"]}
//         />
//         <mesh
//           name="Object_21"
//           geometry={nodes.Object_21.geometry}
//           material={materials["Material.008"]}
//         />
//         <mesh
//           name="Object_23"
//           geometry={nodes.Object_23.geometry}
//           material={materials["Material.017"]}
//           position={[-0.033, 0.616, 1.019]}
//           rotation={[-Math.PI, 0, -Math.PI]}
//           scale={[32.945, 32.945, 33.488]}
//         />
//       </group>
//       <mesh
//         name="Object_4"
//         geometry={nodes.Object_4.geometry}
//         material={materials["Material.003"]}
//       />
//       <mesh
//         name="Object_5"
//         geometry={nodes.Object_5.geometry}
//         material={materials["Material.013"]}
//       />
//       <mesh
//         name="Object_6"
//         geometry={nodes.Object_6.geometry}
//         material={materials["Material.016"]}
//       />
//       <mesh
//         name="Object_7"
//         geometry={nodes.Object_7.geometry}
//         material={materials["Material.004"]}
//       />
//       <mesh
//         name="Object_8"
//         geometry={nodes.Object_8.geometry}
//         material={materials["Material.002"]}
//       />
//       <mesh
//         name="Object_9"
//         geometry={nodes.Object_9.geometry}
//         material={materials["Material.002"]}
//       />
//       <mesh
//         name="Object_10"
//         geometry={nodes.Object_10.geometry}
//         material={materials["Material.002"]}
//       />
//       <mesh
//         name="Object_11"
//         geometry={nodes.Object_11.geometry}
//         material={materials["Material.002"]}
//       />
//       <mesh
//         name="Object_12"
//         geometry={nodes.Object_12.geometry}
//         material={materials["Material.009"]}
//       />
//       <mesh
//         name="Object_13"
//         geometry={nodes.Object_13.geometry}
//         material={materials["Material.009"]}
//       />
//       <mesh
//         name="Object_15"
//         geometry={nodes.Object_15.geometry}
//         material={materials["Material.011"]}
//         position={[-1.454, 0.086, -0.566]}
//       />
//       <mesh
//         name="Object_25"
//         geometry={nodes.Object_25.geometry}
//         material={materials["Material.003"]}
//       />
//       <mesh
//         name="Object_26"
//         geometry={nodes.Object_26.geometry}
//         material={materials["Material.014"]}
//       />
//       <mesh
//         name="Object_28"
//         geometry={nodes.Object_28.geometry}
//         material={materials["Material.010"]}
//         position={[-1.485, 0.086, -0.761]}
//         rotation={[Math.PI, 0, Math.PI / 2]}
//         scale={[-0.005, 0.005, 0.005]}
//       />
//     </group>
//   );
// }

// useGLTF.preload(import.meta.env.BASE_URL + "models/laptop.glb");
